In [146]:
import torch 
from torch import nn
import numpy as np
import random as rnd
import matplotlib
import time
# Set the backend BEFORE importing pyplot
matplotlib.use('Qt5Agg')  # Or 'Qt5Agg', 'WXAgg', etc.

import matplotlib.pyplot as plt

In [38]:
m = 6
n = 7

def rnd_N(n):
    return(int(rnd.random()*n))

def remove_from_tensor(Tensor, element):
    mask = Tensor != element
    Tensor_after_remove = Tensor[mask]
    return(Tensor_after_remove)



def Check_Conections(positionX, positionY, S): # positionY é de cima pra baixo
    List_Connections = torch.tensor([]) # Formato conexão: [X, Y, n], n = 1,2,3,4 para leste, sudeste, sul, sudoeste
    if positionX < n-3:
        if S[positionY][positionX] == S[positionY][positionX+1] == S[positionY][positionX+2] == S[positionY][positionX+3]:
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX, positionY, 1]])), dim=0)
    if positionX > 2:
        if S[positionY][positionX] == S[positionY][positionX-1] == S[positionY][positionX-2] == S[positionY][positionX-3]:
            #List_Connections = List_Connections + [[positionX-3, positionY, 1]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX-3, positionY, 1]])), dim=0)
    if positionY < m-3:
        if S[positionY][positionX] == S[positionY+1][positionX] == S[positionY+2][positionX] == S[positionY+3][positionX]:
            #List_Connections = List_Connections + [[positionX, positionY, 3]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX, positionY, 3]])), dim=0)
    if positionY > 2:
        if S[positionY][positionX] == S[positionY-1][positionX] == S[positionY-2][positionX] == S[positionY-3][positionX]:
            #List_Connections = List_Connections + [[positionX, positionY-3, 3]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX, positionY-3, 3]])), dim=0)

    if positionX < n-3 and positionY < m-3:
        if S[positionY][positionX] == S[positionY+1][positionX+1] == S[positionY+2][positionX+2] == S[positionY+3][positionX+3]:
            #List_Connections = List_Connections + [[positionX, positionY, 2]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX, positionY, 2]])), dim=0)
    if positionX < n-3 and positionY > 2:
        if S[positionY][positionX] == S[positionY-1][positionX+1] == S[positionY-2][positionX+2] == S[positionY-3][positionX+3]:
            #List_Connections = List_Connections + [[positionX+3, positionY-3, 4]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX+3, positionY-3, 4]])), dim=0)
    if positionX > 2 and positionY < m-3:
        if S[positionY][positionX] == S[positionY+1][positionX-1] == S[positionY+2][positionX-2] == S[positionY+3][positionX-3]:
            #List_Connections = List_Connections + [[positionX, positionY, 4]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX, positionY, 4]])), dim=0)
    if positionX > 2 and positionY > 2:
        if S[positionY][positionX] == S[positionY-1][positionX-1] == S[positionY-2][positionX-2] == S[positionY-3][positionX-3]:
            #List_Connections = List_Connections + [[positionX-3, positionY-3, 2]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX-3, positionY-3, 2]])), dim=0)

    if n-2 > positionX > 0:
        if S[positionY][positionX] == S[positionY][positionX-1] == S[positionY][positionX+1] == S[positionY][positionX+2]:
            #List_Connections = List_Connections + [[positionX-1, positionY, 1]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX-1, positionY, 1]])), dim=0)
    if m-2 > positionY > 0:
        if S[positionY][positionX] == S[positionY-1][positionX] == S[positionY+1][positionX] == S[positionY+2][positionX]:
            #List_Connections = List_Connections + [[positionX, positionY-1, 3]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX, positionY-1, 3]])), dim=0)
    if n-2 > positionX > 0 and m-2 > positionY > 0:
        if S[positionY][positionX] == S[positionY-1][positionX-1] == S[positionY+1][positionX+1] == S[positionY+2][positionX+2]:
            #List_Connections = List_Connections + [[positionX-1, positionY-1, 2]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX-1, positionY-1, 2]])), dim=0)
    if n-1 > positionX > 1 and m-2 > positionY > 0:
        if S[positionY][positionX] == S[positionY-1][positionX+1] == S[positionY+1][positionX-1] == S[positionY+2][positionX-2]:
            #List_Connections = List_Connections + [[positionX+1, positionY-1, 4]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX+1, positionY-1, 4]])), dim=0)

    if n-1 > positionX > 1:
        if S[positionY][positionX] == S[positionY][positionX-1] == S[positionY][positionX-2] == S[positionY][positionX+1]:
            #List_Connections = List_Connections + [[positionX-2, positionY, 1]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX-2, positionY, 1]])), dim=0)
    if m-1 > positionY > 1:
        if S[positionY][positionX] == S[positionY-1][positionX] == S[positionY-2][positionX] == S[positionY+1][positionX]:
            #List_Connections = List_Connections + [[positionX, positionY-2, 3]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX, positionY-2, 3]])), dim=0)
    if n-1 > positionX > 1 and m-1 > positionY > 1:
        if S[positionY][positionX] == S[positionY-1][positionX-1] == S[positionY-2][positionX-2] == S[positionY+1][positionX+1]:
            #List_Connections = List_Connections + [[positionX-2, positionY-2, 2]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX-2, positionY-2, 2]])), dim=0)
    if n-2 > positionX > 0 and m-1 > positionY > 1:
        if S[positionY][positionX] == S[positionY-1][positionX+1] == S[positionY-2][positionX+2] == S[positionY+1][positionX-1]:
            #List_Connections = List_Connections + [[positionX+2, positionY-2, 4]]
            List_Connections = torch.cat((List_Connections, torch.tensor([[positionX+2, positionY-2, 4]])), dim=0)

    return(List_Connections.to(device))

class Board:
    def __init__(self):
        self.board_state = torch.zeros(6, 7)
        self.available_moves = torch.tensor([0,1,2,3,4,5,6])
        self.List_Connections_1 = torch.tensor([])
        self.List_Connections_2 = torch.tensor([])
    
    def to(self, device):
        """Moves all internal tensors to the specified device."""
        self.board_state = self.board_state.to(device)
        self.available_moves = self.available_moves.to(device)
        self.List_Connections_1 = self.List_Connections_1.to(device)
        self.List_Connections_2 = self.List_Connections_2.to(device)
        # Return self to allow for chaining: obj = TensorContainer(...).to(device)
        return self
    
    def move(self, player, position):
        S = self.board_state
        A_M = self.available_moves
        LC1 = self.List_Connections_1
        LC2 = self.List_Connections_2
        if position not in A_M:
            print('position not available')
            L = [1]
            for i in range(2): # Isso aqui é só pra dar um erro quando o movimento é ilegal
                L[i] = 1
        else:
            # Atualizando o tabuleiro
            for i in range(6):
                if S[6-i-1][position] == 0:
                    if player == 1:
                        S[6-i-1][position] = 1
                        self.List_Connections_1 = torch.cat((self.List_Connections_1, Check_Conections(position, 6-i-1, S)), dim=0) 
                    else:
                        S[6-i-1][position] = -1
                        self.List_Connections_2 = torch.cat((self.List_Connections_2, Check_Conections(position, 6-i-1, S)), dim=0)
                    if i == 5: # Atualizando a lista de movimentos disponiveis
                        A_M = remove_from_tensor(A_M, position)
                    break
             
            
            self.board_state = S
            self.available_moves = A_M
                

In [28]:
'''          
Tabuleiro = Board()
print(Tabuleiro.board_state)
print(Tabuleiro.available_moves)
Terminou = False
'''

NV1 = 0
NV2 = 0
NV0 = 0

LPV = []
Lx = []
for k in range(1):
    if k > 0 and k%100 == 0:
        print(k, NV1/(NV1+NV2+NV0), NV0/(NV1+NV2+NV0))
    
    
    Tabuleiro = Board()
    Terminou = False
    for i in range(7):
        for j in range(6):
            print(i, j)
            Jogadas_possiveis = Tabuleiro.available_moves
            if j%2 == 1:
                Tabuleiro.move(2, Jogadas_possiveis[rnd_N(len(Jogadas_possiveis))])
            else:
                '''jogada = int(input('Jogada: '))
                Tabuleiro.move(1, jogada)'''
                Tabuleiro.move(1, Jogadas_possiveis[rnd_N(len(Jogadas_possiveis))])
            print(Tabuleiro.board_state)
            print(Tabuleiro.available_moves)
            print(Tabuleiro.List_Connections_1)
            print(Tabuleiro.List_Connections_2)
            
            
            #print(Tabuleiro.board_state)
            #print(Tabuleiro.available_moves)
            #print(Tabuleiro.List_Connections_1)
            #print(Tabuleiro.List_Connections_2)
            '''
            if len(Tabuleiro.List_Connections_1) > 0:
                #print('vitória do jogador 1')
                NV1 = NV1 + 1
                Terminou = True
                break
            if len(Tabuleiro.List_Connections_2) > 0:
                #print('vitória do jogador 2')
                NV2 = NV2 + 1
                Terminou = True
                break'''
        if Terminou == True:
            LPV = LPV + [NV1/(NV1+NV2)]
            Lx = Lx + [k]
            break
    if Terminou == False:
        #print(Tabuleiro.board_state)
        NV0 = NV0 + 1

0 0
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.]])
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([])
tensor([])
0 1
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [8., 0., 0., 0., 0., 1., 0.]])
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([])
tensor([])
0 2
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [8., 0., 0., 0., 1., 1., 0.]])
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([])
tensor([])
0 3
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.

In [17]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

#Tabuleiro = Board().to(device)

'cuda'

In [260]:
'''Depois a gente tem que ver quais tensores require grad e quais não, pra ficar mais eficiente'''


def minimax(Current_board_object, Model, depth, Player): # Player = {1, != 1}
    Current_State = Current_board_object.board_state
    Current_Available_Moves = Current_board_object.available_moves
    if len(Current_board_object.List_Connections_1) > 0:
        return 1, None
    if len(Current_board_object.List_Connections_2) > 0:
        return 0, None
    elif len(Current_Available_Moves) == 0:
        return 0.5, None
    elif depth == 0:
        return Model(Current_State), None

    else:
        if Player == 1: # Player 1 is the maximizer
            
            best_move = Current_Available_Moves[rnd_N(len(Current_Available_Moves))]
            Current_Evaluation = 0 # We start by assuming the worst possible case for player 1
            
            for move in Current_Available_Moves:
                child_board = Board().to(device)
                child_board.board_state = Current_State.clone()
                child_board.available_moves = Current_Available_Moves.clone()
                child_board.move(1, move)
                Evaluation_of_child = minimax(child_board, Model, depth-1, 2)[0]
                if Evaluation_of_child == 1:
                    return 1, move
                if Evaluation_of_child > Current_Evaluation:
                    Current_Evaluation = Evaluation_of_child
                    best_move = move
        else:
            
            Current_Evaluation = 1 # We start by assuming the worst possible case for player 2
            best_move = Current_Available_Moves[rnd_N(len(Current_Available_Moves))]
            
            for move in Current_Available_Moves:
                child_board = Board().to(device)
                child_board.board_state = Current_State.clone()
                child_board.available_moves = Current_Available_Moves.clone()
                child_board.move(2, move)
                Evaluation_of_child = minimax(child_board, Model, depth-1, 1)[0]
                if Evaluation_of_child < Current_Evaluation:
                    Current_Evaluation = Evaluation_of_child
                    best_move = move
        
        
        
        return Current_Evaluation, best_move
                
def minimax_pruned(Current_board_object, Model, depth, Player, alpha, beta): # Player = {1, != 1}
    Current_State = Current_board_object.board_state
    Current_Available_Moves = Current_board_object.available_moves
    if len(Current_board_object.List_Connections_1) > 0:
        return torch.tensor(1).to(device), None
    if len(Current_board_object.List_Connections_2) > 0:
        return torch.tensor(0).to(device), None
    elif len(Current_Available_Moves) == 0:
        return torch.tensor(0.5).to(device), None
    elif depth == 0:
        return Model(Current_State), None

    else:
        if Player == 1: # Player 1 is the maximizer
            
            best_move = Current_Available_Moves[rnd_N(len(Current_Available_Moves))]
            Current_Evaluation = torch.tensor(0) # We start by assuming the worst possible case for player 1
            
            for move in Current_Available_Moves:
                child_board = Board().to(device)
                child_board.board_state = Current_State.clone()
                child_board.available_moves = Current_Available_Moves.clone()
                child_board.move(1, move)
                Evaluation_of_child = minimax_pruned(child_board, Model, depth-1, 2, alpha, beta)[0]
                if Evaluation_of_child == 1:
                    return torch.tensor(1).to(device), move
                if Evaluation_of_child > Current_Evaluation:
                    Current_Evaluation = Evaluation_of_child
                    best_move = move
                alpha = max(alpha, Current_Evaluation)
                if beta <= alpha:
                    break
        else:
            
            Current_Evaluation = torch.tensor(1) # We start by assuming the worst possible case for player 2
            best_move = Current_Available_Moves[rnd_N(len(Current_Available_Moves))]
            
            for move in Current_Available_Moves:
                child_board = Board().to(device)
                child_board.board_state = Current_State.clone()
                child_board.available_moves = Current_Available_Moves.clone()
                child_board.move(2, move)
                Evaluation_of_child = minimax_pruned(child_board, Model, depth-1, 1, alpha, beta)[0]
                if Evaluation_of_child < Current_Evaluation:
                    Current_Evaluation = Evaluation_of_child
                    best_move = move
                if Evaluation_of_child == 0:
                    return torch.tensor(0).to(device), move
                beta = min(beta, Current_Evaluation)
                if beta <= alpha:
                    break
        
        
        return Current_Evaluation.to(device), best_move                

In [219]:
class Model_Connect_4(nn.Module):
    def __init__(self):
        super().__init__()
        # 2. Create 2 nn.Linear layers capable of handling X and y input and output shapes
        self.layer_1 = nn.Linear(in_features=m*n, out_features=10)
        self.layer_2 = nn.Linear(in_features=10, out_features=10) 
        self.layer_3 = nn.Linear(in_features=10, out_features=1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
    # 3. Define a forward method containing the forward pass computation
    def forward(self, x):
        # Return the output of layer_2, a single feature, the same shape as y
        return torch.squeeze(self.sigmoid(self.layer_3(self.relu(self.layer_2(self.relu(self.layer_1(x.reshape(-1)))))))) # computation goes through layer_1 first then the output of layer_1 goes through layer_2

Player_Model = Model_Connect_4().to(device)


In [254]:

Tabuleiro2 = Board().to(device)

for i in range(10):
    Jogadas_possiveis = Tabuleiro2.available_moves
    Tabuleiro2.move((-1)**i, Jogadas_possiveis[rnd_N(len(Jogadas_possiveis))])
print(Tabuleiro2.board_state)
print(Tabuleiro2.List_Connections_1, Tabuleiro2.List_Connections_2)

t1 = time.time()
#print(minimax(Tabuleiro2, Player_Model, 4, 1))
t2 = time.time()
#print(t2-t1)
print(minimax_pruned(Tabuleiro2, Player_Model, 4, 1, 0, 1))
t3 = time.time()
print(t3-t2)


tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [-1.,  0.,  0.,  1.,  0., -1.,  1.],
        [-1.,  1.,  0.,  1., -1.,  1., -1.]], device='cuda:0')
tensor([], device='cuda:0') tensor([], device='cuda:0')
(tensor(0.5176, device='cuda:0', grad_fn=<SqueezeBackward0>), tensor(0, device='cuda:0'))
1.1592140197753906


In [267]:
def training_Batch(N, Player_Model, depth):
    Batch_X = []
    Batch_Y = []
    for game in range(N):
        board = Board().to(device)
        for movement in range(m*n):
            A_M = board.available_moves
            Board_State = board.board_state

            if movement%2 == 0:
                player = 1
            else:
                player = 2

            Batch_X.append(Board_State.clone())

            Evaluation, best_move = minimax_pruned(board, Player_Model, depth, player, 0, 1)
            print(Board_State)
            print(Evaluation, best_move)
            Batch_Y.append(Evaluation) 

            if rnd.random() > 0.0:
                board.move(player, best_move)
            else:
                board.move(player, A_M[rnd_N(len(A_M))])
            
            if len(board.List_Connections_1) > 0 or len(board.List_Connections_2) > 0:
                break

        
        Batch_X.append(board.board_state.clone())
        
        
        if len(board.List_Connections_2) > 0:
            Result = torch.tensor(0).to(device)
        elif len(board.List_Connections_1) > 0:
            Result = torch.tensor(1).to(device)
        else:
            Result = torch.tensor(0.5).to(device)
        Batch_Y.append(Result)

        
    #return Batch_X, Batch_Y         
    return torch.stack(Batch_X, dim=0), torch.stack(Batch_Y, dim=0)

In [269]:
print(training_Batch(2, Player_Model, 4))

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')
tensor(0.5367, device='cuda:0', grad_fn=<SqueezeBackward0>) tensor(4, device='cuda:0')
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]], device='cuda:0')
tensor(0.5408, device='cuda:0', grad_fn=<SqueezeBackward0>) tensor(2, device='cuda:0')
tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0.,  1.,  0.,  0.]], device='cuda:0')
tensor(0.5376, device='cuda:0', grad_fn=<Squee

In [ ]:
''' Aqui começa o loop de treinamento '''